module.exports = {
  MARGIN_XSMALL: 2,
  MARGIN_SMALL: 4,
  MARGIN: 8,
  MARGIN_BIG: 16,
  LEFT_CONTENT_MARGIN: 72,

  ICON_SCALE: 2,

  FONT_MEDIUM: 14,
  FONT_LARGE: 16,
  FONT_XLARGE: 18,

  SESSION_HEADER_ICON: 56,
  SESSION_SPEAKER_IMAGE: 38,

  SESSION_CATEGORY_TITLE_CELL_HEIGHT: 48,
  SESSION_CELL_HEIGHT: 98,
  SESSION_CELL_IMAGE_HEIGHT: 84,
  SESSION_CELL_IMAGE_WIDTH: 112,

  CELL_TYPE_SPACER_HEIGHT: 8,
  CELL_TYPE_SEPARATOR_HEIGHT: 8,
  CELL_TYPE_SMALL_SEPARATOR_HEIGHT: 1,

  LOADING_INDICATOR: 48,
  LOADING_INDICATOR_LINE_WIDTH: 3.5,

  DRAWER_LIST_ITEM_HEIGHT: 48,
  DRAWER_SEPARATOR_HEIGHT: 16,
  DRAWER_USER_TEXT_CONTAINER_HEIGHT: 56,
  DRAWER_USER_AREA_HEIGHT: 120,

  SCHEDULE_PAGE_ITEM_HEIGHT: 120
};
