platform :ios do
  desc "Build the Tabris.js Conference App"
  lane :match do
    match(type: "development", git_url: "git@github.com:eclipsesource/match-certificates.git")
  end
  lane :tabrisBuildDebug do
    sh "cd .. && tabris build ios --device --debug"
  end
  desc "Deploy App to the Appstore"
  lane :deploy do
    #appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end
